
name: ESP32

# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onschedule
on: [push]
jobs:
  esp32_daily:
    runs-on: ubuntu-latest

    name: ESP32 Continuous Builds
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: |
          tensorflow/lite/micro/tools/ci_build/test_esp32.sh
